config/routes.rb
# encoding: UTF-8
LiteraturaComEs::Application.routes.draw do

  get "materias/index"

  get "materias/show"

  get "editoriales/index"

  get "editoriales/show"

  resources :libros
  
  match "/autores/", :to => "autores#index"
  match "/autores/:letra_id-:page/", :constraints => {:letra_id => /[A-Z]/, :page => /[0-9]+/}, :to => "autores#index"
  
  resources :autores
  
  match "/editoriales/", :to => "editoriales#index"
  match "/editoriales/:letra_id-:page/", :constraints => {:letra_id => /[A-Z]/, :page => /[0-9]+/}, :to => "editoriales#index"
  match "/editoriales/:id-:page", :constraints => {:page => /[0-9]+/}, :to => "editoriales#show"

  resources :editoriales
  
  match "/materias/", :to => "materias#index"
  match "/materias/:letra_id-:page/", :constraints => {:letra_id => /[A-Z]/, :page => /[0-9]+/}, :to => "materias#index"
  match "/materias/:id-:page", :constraints => {:page => /[0-9]+/}, :to => "materias#show"
  
  resources :materias

  match "/busquedas/:busqueda_id/:tipo/:id" => "busquedas#show"
  
  resources :busquedas do
    resources :libros,:trailing_slash => true, :tipo=>'libros'
    resources :autores,:trailing_slash => true, :tipo=>'autores'
    resources :editoriales,:trailing_slash => true, :tipo=>'editoriales'
    resources :materias,:trailing_slash => true, :tipo=>'materias'
  end
  
  match "/epocas/", :to => "annos#index" 
  match "/epocas/siglo/:siglo", :to => "annos#index" #-:page", :constraints => {:siglo => /[XVI]+/, :page => /[0-9]+/}, :to => "annos#index"
  match "/epocas/siglo/:siglo/anno/:anno-:page", :to => "annos#show"

  match "/politica_de_privacidad.html", :to => 'base#politica_de_privacidad'
  match "/contacto.html", :to => 'base#contacto'
  match "/acerca_de.html", :to => 'base#acerca_de'

  root :to => 'libros#index'
end

app/models/busqueda.rb
class Busqueda
  attr :texto
  attr_reader :libros
  attr_reader :autores
  attr_reader :editoriales
  attr_reader :materias
  attr_reader :data
  
  def to_param
    texto
  end
  
  def initialize(_texto=nil,_tipo=nil,_page=1)
    @libros = []
    @autores = []
    @editoriales = []
    @materias = []
    @texto = _texto
    return unless _tipo || _texto
    case _tipo # Mostramos la primera pagina de todos
      when nil
        # Vamos a mostrar 20 resultados
        @autores = Autor.search _texto, :order => :nombre, :per_page => 5
        @editoriales = Editorial.search _texto, :order => :nombre, :per_page => 5
        @materias = Materia.search _texto, :order => :nombre, :per_page => 5
        @libros = Libro.search _texto, :order => :titulo, :per_page => (20-@autores.size-@editoriales.size-@materias.size)
      when 'libros'
        @data = Libro.search _texto, :per_page => 20, :page => _page
      else 
        @data = eval("#{_tipo.singularize.capitalize}.search '#{_texto}', :order => :nombre, :per_page => 20, :page => #{_page}")
      end
  end
end

app/controllers/busquedas_controller.rb
# encoding: UTF-8
class BusquedasController < ApplicationController
  def show
    add_crumb "Búsquedas",'#'
    
    if params[:busqueda_id]
      @busqueda = Busqueda.new(params[:busqueda_id],params[:tipo],params[:id])
      
      add_crumb params[:busqueda_id],'#'
      add_crumb "Página #{params[:id]}"
      
      # @keywords = "tesis búsquedas #{params[:busqueda_id]}"
      # @meta = "Búsqueda por #{params[:tipo]} - #{params[:busqueda_id]}"
      # @title = "#{@meta} - Tesis - tesis.com.es"
    else
      @busqueda = Busqueda.new(params[:id])
      
      add_crumb params[:id]
      
      
      # @keywords = "tesis búsquedas #{params[:id]}"
      # @meta = "Búsqueda: #{params[:id]}"
      # @title = "#{@meta} - Tesis - tesis.com.es"
    end

    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.xml  { render :xml => @busqueda }
    # end
  end
  
  def create
    params[:busqueda]='Internet para torpes' if params[:busqueda]=="" 
    @busqueda = Busqueda.new(params[:busqueda])
    
    #add_crumb "Búsquedas"
    #add_crumb params[:busqueda][:texto]
    
    
    # @keywords = "tesis búsquedas #{params[:busqueda][:texto]}"
    # @meta = "Búsqueda: #{params[:busqueda][:texto]}"
    # @title = "#{@meta} - Tesis - tesis.com.es"
    
    redirect_to :action => :show, :id => params[:busqueda]
  end

end

app/helpers/busquedas_helper.rb
module BusquedasHelper
end

app/views/busquedas/show.html.erb
<h1>Resultados</h1>
<h2>Para la búsqueda <%= @busqueda.texto %></h2>

<div id="ficha">
  <% if params[:busqueda_id] %> <%#= Resultados de un solo tipo %>
    <ul class="resultados">
      <li><%= params[:tipo].capitalize %><hr/></li>
      <% for dato in @busqueda.data %>
        <li><%= link_to raw(dato.nombre.force_encoding('UTF-8')),eval("#{dato.class.name.downcase}_url('#{dato.pretty_name}')") %><hr/></li>
      <% end %>
    </ul>
    <div id="paginacion">
      <%= will_paginate @busqueda.data , :controller => 'busquedas', :renderer => 'ApplicationHelper::RestLinkRenderer' %>
    </div>
  <% else %>

    <% if params[:tipo] %> <%#= ERROR? %>


    <% else %> <%#= Resultado normal con varios tipos %>
      <ul class="resultados">
        <% if @busqueda.libros.size>0 %>
          <li>LIBROS<hr/></li> 
          <% for libro in @busqueda.libros %>
            <li><%= link_to raw(libro.nombre.force_encoding('UTF-8')),eval("#{libro.class.name.downcase}_url('#{libro.pretty_name}')") %><hr/></li>
          <% end %>
          <li><img class="ico-mas" src="/images/ico-mas.jpg" width="16" height="16" /><%= link_to "Mas resultados", busqueda_libro_url(@busqueda.texto,1), :class=>"mas-resultados" %><hr /></li>
        <% end %>
        <% if @busqueda.autores.size>0 %>
          <li>AUTORES<hr/></li> 
          <% for autor in @busqueda.autores %>
            <li><%= link_to raw(autor.nombre.force_encoding('UTF-8')), autor_url(autor.pretty_name)%><hr /></li>
          <% end %>
          <li><img class="ico-mas" src="/images/ico-mas.jpg" width="16" height="16" /><%= link_to "Mas resultados", busqueda_autor_url(@busqueda.texto,1), :class=>"mas-resultados" %><hr /></li>
        <% end %>
        <% if @busqueda.editoriales.size>0 %>
          <li>EDITORIALES<hr/></li> 
          <% for editorial in @busqueda.editoriales %>
            <li><%= link_to raw(editorial.nombre.force_encoding('UTF-8')), editorial_url(editorial.pretty_name)%><hr /></li>
          <% end %>
          <li><img class="ico-mas" src="/images/ico-mas.jpg" width="16" height="16" /><%= link_to "Mas resultados", busqueda_editorial_url(@busqueda.texto,1), :class=>"mas-resultados" %><hr /></li>
        <% end %>
        <% if @busqueda.materias.size>0 %>
          <li>MATERIAS<hr/></li> 
          <% for materia in @busqueda.materias %>
            <li><%= link_to raw(materia.nombre.force_encoding('UTF-8')), materia_url(materia.pretty_name)%><hr /></li>
          <% end %>
          <li><img class="ico-mas" src="/images/ico-mas.jpg" width="16" height="16" /><%= link_to "Mas resultados", busqueda_materia_url(@busqueda.texto,1), :class=>"mas-resultados" %><hr /></li>
        <% end %>
      </ul>
    <% end %>

  <% end %>
</div>