config/routes.rb
# encoding: UTF-8
LiteraturaComEs::Application.routes.draw do

  get "materias/index"

  get "materias/show"

  get "editoriales/index"

  get "editoriales/show"

  resources :libros
  
  match "/autores/", :to => "autores#index"
  match "/autores/:letra_id-:page/", :constraints => {:letra_id => /[A-Z]/, :page => /[0-9]+/}, :to => "autores#index"
  
  resources :autores
  
  match "/editoriales/", :to => "editoriales#index"
  match "/editoriales/:letra_id-:page/", :constraints => {:letra_id => /[A-Z]/, :page => /[0-9]+/}, :to => "editoriales#index"
  match "/editoriales/:id-:page", :constraints => {:page => /[0-9]+/}, :to => "editoriales#show"

  resources :editoriales
  
  match "/materias/", :to => "materias#index"
  match "/materias/:letra_id-:page/", :constraints => {:letra_id => /[A-Z]/, :page => /[0-9]+/}, :to => "materias#index"
  match "/materias/:id-:page", :constraints => {:page => /[0-9]+/}, :to => "materias#show"
  
  resources :materias

  match "/busquedas/:busqueda_id/:tipo/:id" => "busquedas#show"
  
  resources :busquedas do
    resources :libros,:trailing_slash => true, :tipo=>'libros'
    resources :autores,:trailing_slash => true, :tipo=>'autores'
    resources :editoriales,:trailing_slash => true, :tipo=>'editoriales'
    resources :materias,:trailing_slash => true, :tipo=>'materias'
  end
  
  match "/epocas/", :to => "annos#index" 
  match "/epocas/siglo/:siglo", :to => "annos#index" #-:page", :constraints => {:siglo => /[XVI]+/, :page => /[0-9]+/}, :to => "annos#index"
  match "/epocas/siglo/:siglo/anno/:anno-:page", :to => "annos#show"

  match "/politica_de_privacidad.html", :to => 'base#politica_de_privacidad'
  match "/contacto.html", :to => 'base#contacto'
  match "/acerca_de.html", :to => 'base#acerca_de'

  root :to => 'libros#index'
end

app/views/shared/_buscador.html.erb
<span id="buscador-titulo">Buscar</span> 
<% form_for :busqueda, nil, :url => busquedas_url, :html => {:id => 'buscador'} do |f| -%>
	<input id="cuadro-busqueda" name="busqueda" type="text" /> 
  	<input type="image" name="Submit" value="Submit" src="/images/lupa-buscador.jpg">     
<% end -%>

app/views/shared/_cabecera.html.erb
<%= render :partial => 'shared/camino' %>

app/views/shared/_camino.html.erb
<%= raw (render_crumbs :ul_id => 'breadcrumb', :format => :html_list, :active_li_class => 'end') %>

app/views/shared/_menu.html.erb
<%= image_tag "logo-b.jpg", :id=> 'logo' %>



<ul id="menu">
	<li>
		<%= image_tag "ico-home.gif", :class => 'ico' %> <%= link_to "Home","/" %><span>para que siempre empices con buen pie</span>
		<img class="linea-menu" src="/images/linea-menu.gif" width="237" height="3" />
	</li>
	<li>
		<%= image_tag "ico-autores.gif", :class => 'ico' %> <%= link_to "Autores","/autores/" %><span>todos los autores españoles e internacionales</span>
		<img class="linea-menu" src="/images/linea-menu.gif" width="237" height="3" />
	</li>
	<li>
		<%= image_tag "ico-epocas.gif", :class => 'ico' %> <a href="/epocas/">Epocas</a><span>de los manuscritos iluminados al siglo XXI</span>
		<img class="linea-menu" src="/images/linea-menu.gif" width="237" height="3" />
	</li>
	<li>
		<%= image_tag "ico-editoriales.gif", :class => 'ico' %> <a href="/editoriales/">Editoriales</a><span>los editores desde la invencion de la imprenta</span>
		<img class="linea-menu" src="/images/linea-menu.gif" width="237" height="3" />
	</li>
	<li>
		<%= image_tag "ico-materias.gif", :class => 'ico' %> <a href="/materias/">Materias</a><span>de la alquimia a la astrofisica</span>
		<img class="linea-menu" src="/images/linea-menu.gif" width="237" height="3" />
	</li>
</ul>

<%= render :partial => 'shared/buscador' %>

<img class="linea-separa" src="/images/linea-menu.gif" width="237" height="3" />
          
<span id="submenu"><a href="/contacto.html">CONTACTO</a>-<a href="/politica_de_privacidad.html">PRIVACIDAD</a>-<a href="/acerca_de.html">ACERCA DE ESTA WEB</a></span>

app/views/shared/_pie.html.erb
pie