config/routes.rb
# encoding: UTF-8
LiteraturaComEs::Application.routes.draw do

  get "materias/index"

  get "materias/show"

  get "editoriales/index"

  get "editoriales/show"

  resources :libros
  
  match "/autores/", :to => "autores#index"
  match "/autores/:letra_id-:page/", :constraints => {:letra_id => /[A-Z]/, :page => /[0-9]+/}, :to => "autores#index"
  
  resources :autores
  
  match "/editoriales/", :to => "editoriales#index"
  match "/editoriales/:letra_id-:page/", :constraints => {:letra_id => /[A-Z]/, :page => /[0-9]+/}, :to => "editoriales#index"
  match "/editoriales/:id-:page", :constraints => {:page => /[0-9]+/}, :to => "editoriales#show"

  resources :editoriales
  
  match "/materias/", :to => "materias#index"
  match "/materias/:letra_id-:page/", :constraints => {:letra_id => /[A-Z]/, :page => /[0-9]+/}, :to => "materias#index"
  match "/materias/:id-:page", :constraints => {:page => /[0-9]+/}, :to => "materias#show"
  
  resources :materias

  match "/busquedas/:busqueda_id/:tipo/:id" => "busquedas#show"
  
  resources :busquedas do
    resources :libros,:trailing_slash => true, :tipo=>'libros'
    resources :autores,:trailing_slash => true, :tipo=>'autores'
    resources :editoriales,:trailing_slash => true, :tipo=>'editoriales'
    resources :materias,:trailing_slash => true, :tipo=>'materias'
  end
  
  match "/epocas/", :to => "annos#index" 
  match "/epocas/siglo/:siglo", :to => "annos#index" #-:page", :constraints => {:siglo => /[XVI]+/, :page => /[0-9]+/}, :to => "annos#index"
  match "/epocas/siglo/:siglo/anno/:anno-:page", :to => "annos#show"

  match "/politica_de_privacidad.html", :to => 'base#politica_de_privacidad'
  match "/contacto.html", :to => 'base#contacto'
  match "/acerca_de.html", :to => 'base#acerca_de'

  root :to => 'libros#index'
end

app/models/materia.rb
class Materia < ActiveRecord::Base
  include PrettyNames::InstanceMethods
  extend PrettyNames::ClassMethods

  before_save :arreglar_pretty_name

  define_index do
    indexes nombre, :sortable => true
  end

end

app/controllers/materias_controller.rb
# encoding: UTF-8
class MateriasController < ApplicationController
  caches_action :index, :cache_path => Proc.new { |controller| "materias:#{controller.params[:letra_id]}:#{controller.params[:page]}" }
  caches_action :show, :cache_path => Proc.new { |controller| "materias:#{controller.params[:id]}:#{controller.params[:page]}" } 
  def index
    if params[:letra_id] # Listado por letra
      
      add_crumb 'Materias', materias_url
      add_crumb params[:letra_id], "/materias/#{params[:letra_id]}-1/"
      add_crumb "Página #{params[:page]}"
      
      @materias = Materia.paginate :page => params[:page], :order => 'nombre', :conditions => ['letra=?', params[:letra_id]]
      
      sql = "SELECT DISTINCT letra FROM materias"
      letras = ActiveRecord::Base.connection.execute(sql)
      @letras = []
      letras.each { |e| @letras << e[0] if e[0]!=nil && e[0].match(/[A-Za-z]/)!=nil}
    
    else # Listado general de autores
      
      add_crumb 'Materias'
    
      sql = "SELECT DISTINCT letra FROM materias"
      letras = ActiveRecord::Base.connection.execute(sql)
      @letras = {}
    
      letras.each { |e|
        next unless e[0]!=nil && e[0].match(/[A-Za-z]/)!=nil
        primero = Materia.find(:first, :conditions => ['letra=?',e[0]], :order => 'nombre').nombre.capitalize.split(',')[0][0..10]
        ultimo = Materia.find(:last, :conditions => ['letra=?',e[0]], :order => 'nombre').nombre.capitalize.split(',')[0][0..10]

        @letras[e[0]] = [primero,ultimo]
      }
      
      keys = @letras.keys.sort
      
      @letrasA = @letras.select {|k,v| keys[0..10].include?(k)}
      @letrasB = @letras.select {|k,v| keys[11..21].include?(k)}
      @letrasC = @letras.select {|k,v| keys[22..-1].include?(k)}
      # @letrasB = @letras[(@letras.size/3+1)..(2*@letras.size/3)]
      # @letrasC = @letras[((2*@letras.size/3)+1)..-1]
      #@letras['Otros'] = 
    end
  end

  def show
    @materia = Materia.find_by_pretty_name(params[:id])
    libros = Libro.find_all_by_materia(@materia.nombre) #, :order => 'coalesce(titulo_uniforme,titulo),anno,CASE idioma WHEN "spa" THEN 0 ELSE 1 END')

    # Si utilizamos coalesce para ordenar no usa el indice
    lbs = {}
    libros.each {|l|
      key = "#{l.titulo_uniforme!},#{l.anno},#{l.idioma=='spa'?0:1}"
      lbs[key] = l
    }


    add_crumb 'Materias', materias_url
    add_crumb @materia.nombre,"/materias/#{@materia.nombre}-1"
    add_crumb "Página #{params[:page]}"
    
    # @annos = {}
    #     libros.each { |libro|  
    #       @annos[libro.anno] = [] unless @annos[libro.anno] != nil
    #       @annos[libro.anno] << libro
    #     }
    @titulos = {}
    libros.each { |libro| 
      next unless @titulos[libro.titulo_uniforme!]==nil 
      @titulos[libro.titulo_uniforme!] = libro
    }

    ids = []
    @titulos.keys.each { |k|  
      ids << @titulos[k].id
    }
    
    @libros = Libro.by_ids(ids).page(params[:page]).order('titulo')

  end

end

app/helpers/materias_helper.rb
module MateriasHelper
end

app/views/materias/index.html.erb
<h1>Materias</h1>
<h2>todos las materias</h2>

<div id="ficha">
<% if params[:letra_id]%>
	<ul class="listadoB">		
		<% for materia in @materias %>
                  <% next unless materia.pretty_name!='' %>
                        <li>
				<%= link_to materia.nombre, materia_url(materia.pretty_name) %><hr/>
			</li>
		<% end %>		
	</ul>
	<div id="abc">
          <span class="capital"><%= params[:letra_id].upcase %></span><span class="info"><%= "( página #{params[:page]} de #{@materias.total_pages} )"%></span>
		<br /> 
		<span class="letras">
		<% for letra in @letras  %>
			<% if letra.upcase!=params[:letra_id]%>
				<%= link_to letra.upcase,"/materias/#{letra.upcase}-1"%>
			<% end%>
		<% end %>
		</span>
	</div>
</div>
	<br class="limpia" /> 
	<div id="paginacion">
	<%= will_paginate @materias, :controller => 'materias', :id => params[:letra_id], :renderer => 'ApplicationHelper::RestLinkRenderer' %>
	</div>
<% else %>
	<ul class="listadoA"> <%# Columna 1 %>
		<% for letra in @letrasA.keys.sort %>
			<li>
				<%= link_to letra.upcase, "/materias/#{letra.upcase}-1/" %> de <%= @letras[letra][0] %> a <%= @letras[letra][1] %><br/><hr/>
			</li>
		<% end %>
	</ul>
	<ul class="listadoA"> <%# Columna 2 %>
		<% for letra in @letrasB.keys.sort %>
			<li>
				<%= link_to letra.upcase, "/materias/#{letra.upcase}-1/" %> de <%= @letras[letra][0] %> a <%= @letras[letra][1] %><br/><hr/>
			</li>
		<% end %>
	</ul>
	
	<ul class="listadoA dcha"> <%# Columna 2 %>
		<% for letra in @letrasC.keys.sort %>
			<li>
				<%= link_to letra.upcase, "/materias/#{letra.upcase}-1/" %> de <%= @letras[letra][0] %> a <%= @letras[letra][1] %><br/><hr/>
			</li>
		<% end %>
	</ul>

	

<% end %>

app/views/materias/show.html.erb
<h1><%= @materia.nombre %></h1>
<h2>libros catalogados en esta materia</h2>
<div id="ficha">
<ul class="resultados">
  <% for libro in @libros %>
    <li><%= link_to libro.nombre, libro_url(libro.pretty_name)%><hr/></li>
  <% end %>
</ul>
</div>
<div id="paginacion">
  <%= will_paginate @libros, :controller => 'materias', :id => params[:id], :renderer => 'ApplicationHelper::RestLinkRenderer' %>
</div>